falcony-io/sqlalchemy-searchable

docs/installation.rst, sqlalchemy_searchable/__init__.py, tests/test_searchable.py
I haven't actually been able to run the tests, so help with that would be great.  Otherwise, hopefully this is pretty straightforward.
=> New optional `sort` parameter orders results by search rank

sqlalchemy_searchable/parser.py
- Add 'Lo' to alphanumeric categories
Some characters are categorized as 'Lo' by general category in unicode.
For example, Korean character '가' and Japanese character  'は' are categorized as 'Lo'.
It also fix #50.
P.S. 'Lo' means just Letter: http://www.unicode.org/reports/tr44/#General_Category_Values
=> Support unicode letters

sqlalchemy_searchable/__init__.py
Just by creating an `Index`, it's automatically added to its column's table's `indexes` list. There's no need to mess with `__table_args__`, and in fact it breaks classes which implement a `@declared_attr` `__table_args__`. This patch removes the `__table_args__` manipulation in `append_index`, leaving only the Index creation.
=> Eliminate manipulation of __table_args__

sqlalchemy_searchable/__init__.py
Do not use `__table__` attribute in column inspection as it may have not
been set at that point of time. Refs #63.
=> Fix Flask-Sqlalchemy support

docs/configuration.rst
Current code snipet raises: 
```InvalidRequestError: Table 'article' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.```
=> fix code snippet configuration.rst

.travis.yml, setup.py, tox.ini
This fixes the CI build which is currently broken for many reasons.
* **Restrict SQLAlchemy version in Tox envs**
Restrict the SQLAlchemy version to `>=1.3,<1.4` when running the tests with Tox. This also prepares the Tox configuration so that it is easy to add SQLAlchemy 1.4 to the test matrix once SQLAlchemy-Searchable supports it (#100).
* **Use Tox for running the tests and linting in CI**
This makes the tests pass in CI because for some Python versions SQLAlchemy 1.4 got installed which SQLAlchemy-Searchable does not yet support. This also makes the CI environment more consistent with how the tests are run locally and it will make it simple add SQLAlchemy 1.4 to the CI test matrix once SQLAlchemy-Seachable supports it.
* **Pin `attrs` for Python 3.4**
`attrs` dropped Python 3.4 …
=> Use Tox for running the tests and linting in CI

setup.py
The tests fail on SQLAlchemy <1.3.0 with the following error:
tests/__init__.py:10: in <module>
from sqlalchemy.orm.session import close_all_sessions
E   ImportError: cannot import name 'close_all_sessions'
[`close_all_sessions`][1] function was added in SQLAlchemy 1.3.
[1]: https://docs.sqlalchemy.org/en/14/orm/session_api.html?highlight=close_all_sessions#sqlalchemy.orm.close_all_sessions
=> Fix required SQLAlchemy version

.github/workflows/test.yml, CHANGES.rst, docs/installation.rst, setup.py, tox.ini
Drop support for Python 3.6 and 3.7, which have reached the end of their lives. See https://endoflife.date/python.
=> feat!: drop python 3.6 and 3.7 support

CHANGES.rst, setup.py
`validators` package was not used anywhere. Remove the dependency.
=> build: remove validators dependency

docs/conf.py, pyproject.toml, tests/__init__.py, tox.ini
Use [Ruff][1] for linting. This replaces both isort and flake8.
[1]: https://beta.ruff.rs/docs/
=> build: use ruff for linting

tox.ini
Set environment variable `SQLALCHEMY_WARN_20=1` to show all SQLAlchemy 2.0 deprecation warnings when running the tests with tox.
Refs #111
=> test: turn on sqlalchemy 2 deprecation warnings

CHANGES.rst, docs/configuration.rst, docs/installation.rst, pyproject.toml, sqlalchemy_searchable/__init__.py, tests/__init__.py, tests/test_drop_trigger.py, tests/test_sql_functions.py, tests/test_sync_trigger.py, tests/test_weighted_search_vector.py
=> Resolve all sqlalchemy.exc.RemovedIn20Warnings

tests/__init__.py
Pass `future=True` flag to `create_engine`, `sessionmaker` and `Session` in tests.
Refs #111.
=> test: use the future flag on Engine and session

.github/workflows/test.yml, CHANGES.rst, pyproject.toml, sqlalchemy_searchable/__init__.py, tox.ini
Test against SQLAlchemy 2.0 and update the SQLAlchemy dependency to remove the `<1.5` version restriction.
Closes #111. Closes #109.
=> feat: add support for sqlalchemy 2.0

sqlalchemy_searchable/__init__.py
Fix the following deprecation warning:
SADeprecationWarning: The `sqlalchemy.orm.mapper()` symbol is
deprecated and will be removed in a future release. For the
mapper-wide event target, use the 'sqlalchemy.orm.Mapper' class.
=> fix: remove deprecation warning for sqlalchemy.orm.mapper()

docs/search_query_parser.rst
Rewrite the whole chapter search query parser chapter. Update it to reflect the changes to the parser in 1.3.0 and 1.4.0:
- Remove mentions about an explicit `AND` operator
- Remove mentions about using parenthesis for grouping
- Update the internals section to use the correct function name
=> docs: update search query parser docs

.github/workflows/test.yml, CHANGES.rst, tests/conftest.py, tests/test_sql_functions.py
In PostgreSQL 14, [`websearch_to_tsquery()` has been fixed to properly parse query text containing discarded tokens][1]. This affected the tests for `parse_websearch()` which is using `websearch_to_tsquery()` under the hood. Also, add PostgreSQL versions 11, 13, 14 and 15 to the build matrix. Previously, the tests were only run on PostgreSQL 12.
[1]: https://www.postgresql.org/docs/14/release-14.html
=> test: fix 'parse_websearch' tests on PostgreSQL 14 and later 

docs/vectorizers.rst, sqlalchemy_searchable/__init__.py, sqlalchemy_searchable/vectorizers.py
Rewrite the vectorizer documentation:
- Ensure the code examples are up-to-date and working
- Move the documentation from the module docstring to `docs/vectorizers.rst` to be consistent with other documentation.
- Fix grammar and formatting issues
- Add the `vectorizer` object and the `clear` method to the API section.
=> docs: improve vectorizer documentation

docs/integrations.rst
- Fix some grammar and formatting issues
- Add a warning that the query interface is considered legacy in SQLAlchemy. Use more neutral language not to encourage using the `SearchQueryMixin` class anymore.
- Ensure the code examples work.
- Remove the note about Python 2 since we don't support it anymore.
=> docs: improve Flask-SQLAlchemy integration documentation

docs/configuration.rst, docs/quickstart.rst, sqlalchemy_searchable/__init__.py
Fix grammar and formatting issues. Ensure the code examples work.
=> docs: improve configuration documentation

CHANGES.rst
Update the changelog to include the missing changes since 1.4.1
=> docs: update the changelog

CHANGES.rst, docs/quickstart.rst, tests/test_multiple_vectors_per_class.py, tests/test_searchable.py, tests/test_weighted_search_vector.py
The query interface is legacy in SQLAlchemy 2.0. Migrate the tests and documentation to use the `Session.execute()` in conjunction with `select()` to run ORM queries. The documentation and tests regarding `SearchQueryMixin` continue using the legacy query API.
=> refactor: migrate from legacy query API to select()

tests/conftest.py
`remove_symbols` option was removed in 1.0.0
=> test: remove `remove_symbols` mentions
